#!/bin/bash

SCREENSHOT_DIR="$HOME/Pictures/Screenshots"

mkdir -p "$SCREENSHOT_DIR"

chosen=$(echo -e "🖼️  Full Screen\n🔲  Region\n📋  Clipboard Only\n📁  Open Screenshots" | wofi --dmenu --prompt="Screenshot Menu" --style="$HOME/.config/wofi/menu.css")

option=$(echo "$chosen" | awk '{print $2}')

case "$option" in
    Full) 
        echo ":: Taking full-screen screenshot"
        sleep 0.5
        hyprshot -m region -o "$SCREENSHOT_DIR"
        ;;
    Region) 
        echo ":: Taking region screenshot"
        sleep 0.5
        hyprshot -m window -o "$SCREENSHOT_DIR"
        ;;
    Clipboard) 
        echo ":: Taking screenshot and copying to clipboard only"
        sleep 0.5
        hyprshot -m output --clipboard-only # Adding clipboard option
        ;;
    Open) 
        echo ":: Opening screenshots folder"
        sleep 0.5
        xdg-open "$SCREENSHOT_DIR"
        ;;
    *) 
        echo "No valid option selected"
        ;;
esac

